### PR TITLE
Add lifecycle hooks for Executor

### PR DESCRIPTION
**Pull request by kakubin**
*Issue #, if available:*

In order to use [job-iteration](https://github.com/Shopify/job-iteration) and [maintenance_tasks](https://github.com/Shopify/maintenance_tasks) with aws-activejob-sqs, it should have the functionality for broadcasting terminal events.
these would be used for job-iteration to know when the worker is going to stop.

By submitting this pull request, I confirm that my contribution is made under
the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by mullermp** [comment]
Thanks for opening a pull request. On the surface, this makes sense. I looked around in the source code for job-iteration. I'm wondering, could you show me specifically where lifecycle hooks are necessary? It seems that they only require jobs to have the enumerable interfaces. My other question is - does an sqs adapter need to be added to their gem?

As far as testing goes, does it make sense to have a test dependency on job-iteration and write a higher level test using it? Otherwise it's not entirely clear why we have lifecycle hooks. Perhaps also adding an entry to the readme about how to stop (and resume?) jobs.

**Comment by kakubin** [comment]
In job-iteration, [`JobIteration::Iteration#job_should_exit?`](https://github.com/Shopify/job-iteration/blob/5865a9f599a4610e436d47db271517d9f254552b/lib/job-iteration/iteration.rb#L290-L295)(which module will be included to ApplicationJob) is called for each iteration of a job to check whether the processing could continue.

The interruption adapter referenced there needs to reflect the state of the worker, and an adapter is required for each job's backend implementation. 
> does an sqs adapter need to be added to their gem?

Partially yes.
Below is the specific code I have in mind:
```rb
module JobIteration
  module InterruptionAdapters
    module SqsAdapter
      class << self
        attr_accessor :stopping

        def call
          stopping
        end
      end

      Aws::ActiveJob::SQS.on_worker_stop do
        SqsAdapter.stopping = true
      end
    end

    register(:sqs, SqsAdapter)
  end
end
```
It seems that aws-activejob-sqs does not have an interface to reference the worker's state from the outside, so I wanted to add a hook for this purpose. I wasn't sure whether to include this adapter here or have it added to their gem, so I decided to limit the change to adding the hook for now.
As for preparing tests for job-iteration, it depends on where the adapter exists.

**Review by alextwoods — APPROVED** [review]
Thanks for adding these - I agree adding the stop life cycle hook makes sense for this.  I have a slight preference for the adapters living in their gems instead of in here, but either way, we should be able to merge this change

**Comment by kakubin** [comment]
@mullermp 
I will ask them after merged.
Please tell me if there's anything I can do right now.

**Pull request merged**
